### PR TITLE
Update docs with Resultify-Math and more changes

### PR DESCRIPTION
**Pull request by dfellis**
This updates the docs with the new changes to the language. Mostly due to Resultify-Math, but also other changes that we had forgotten about.

### CODE REVIEW

**Comment by depombo** [comment]
The function signatures are too dense and will force someone getting acquainted with Alan for the first time to just skim them without grasping how Alan is different and unique. I think showing how math is safe is Alan makes much more sense by example.

That said, I am happy to stamp this since it is consistent with everything else. I'm not sure if I mentioned this but right before or right after the 0.2 release I was thinking about redoing and trimming a lot of the docs. Right now we have just added stuff without thinking too hard of the ergonomics / UX of it -- namely what do people want to know and making that information quick to find. I thinking less is more in this case and we have too much documentation as of right now.

**Review by depombo — APPROVED** [review]

**Comment by dfellis** [comment]
> The function signatures are too dense and will force someone getting acquainted with Alan for the first time to just skim them without grasping how Alan is different and unique. I think showing how math in safe is Alan makes much more sense by example.
> 
> That said, I am happy to stamp this since it is consistent with everything else. I'm not sure if I mentioned this but right before or right after the 0.2 release I was thinking about redoing and trimming a lot of the docs. Right now we have just added stuff without thinking too hard of the ergonomics / UX of it -- namely what do people want to know and making that information quick to find. I thinking less is more in this case and we have too much documentation as of right now.

I wouldn't want to trim it. This is the "Reference Manual" that should be as complete as possible for anyone trying to figure out particular edge cases.

But I do agree that *something else* should be the documentation that most people grab first.

**Comment by depombo** [comment]
So what you are saying is that what we currently have as "documentation" becomes the "reference manual" and then we have a more friendly introduction that is created and becomes the "documentation"?

**Comment by dfellis** [comment]
> So what you are saying is that what we currently have as "documentation" becomes the "reference manual" and then we have a more friendly introduction that is created and becomes the "documentation"?

Yes. I prioritized this form first because advanced developers shouldn't be too put off by it (who are the only ones who should really be playing with Alan right now) and it requires less effort to update if/when we change some language behaviors, while a clearer set of documentation introducing the language will require more prose and that prose could be seriously impacted by the alpha-level changes we've been making to it.

**Comment by depombo** [comment]
> Yes. I prioritized this form first because advanced developers shouldn't be too put off by it (who are the only ones who should really be playing with Alan right now) and it requires less effort to update if/when we change some language behaviors, while a clearer set of documentation introducing the language will require more prose and that prose could be seriously impacted by the alpha-level changes we've been making to it.

Got it, yeah I was thinking of what we saw a few months back and we both liked -- https://vale.dev/guide/introduction

**Pull request merged**
